### ISSUE TITLE
Wrong Installation

### ISSUE THREAD

**Issue by InforPsico** [hostmoz/laravel-bootstrap-starter-kit#1]
In the documentation, you've stated that the installation link is: Laravel new --using=shipfastlabs/modern-react-starter-kit modern-react-app

It's impossible to install this package. How about adding the correct one?

**Comment by backstageel** [comment]
Hello, The link is already fixed. Thanks

**Comment by InforPsico** [comment]
It seems the command is still broken. If you try it, you'll see why. Have you actually tried the command? It seems like you don't want people to install your package.
